#!/bin/bash

#make SOC=gxb distclean
make distclean

export PATH=$PATH:/opt/gcc-linaro-aarch64-none-elf-4.8-2013.11_linux/bin/
export PATH=$PATH:/opt/CodeSourcery/Sourcery_G++_Lite/bin
#export PATH=$PATH:/~/Amlogic_S905-u-boot/tolchain/bin

ARCH=arm64 CROSS_COMPILE=aarch64-none-elf- make  gxb_p200_v1_config
ARCH=arm64 CROSS_COMPILE=aarch64-none-elf- make -j
