#!/bin/bash

#make SOC=gxb distclean
make distclean

#export PATH=$PATH:/opt/gcc-linaro-aarch64-none-elf-4.8-2013.11_linux/bin/
#export PATH=$PATH:/opt/CodeSourcery/Sourcery_G++_Lite/bin

ARCH=arm64 make  gxb_p200_v1_config
#CROSS_COMPILE=aarch64-none-elf- make  gxb_p200_v1_config
ARCH=arm64 make -j
#CROSS_COMPILE=aarch64-none-elf- make -j
