#!/bin/bash

make SOC=gxb distclean

export PATH=$PATH:/opt/gcc-linaro-aarch64-none-elf-4.8-2013.11_linux/bin/
export PATH=$PATH:/opt/CodeSourcery/Sourcery_G++_Lite/bin

ARCH=arm64 CROSS_COMPILE=aarch64-none-elf- make  gxb_p201_v1_config
ARCH=arm64 CROSS_COMPILE=aarch64-none-elf- make -j4
